project: test
save_path: ./checkpoints/gsm-coconut
name: llama+GSM8k+Residual+Cosine_Regularization

only_eval: False

# 核心配置
coconut: True
decoupling_mode: "residual"
cot: False
no_thoughts: False
no_cot: False

# 难度设置
c_thought: 6
epochs_per_stage: 3
max_latent_stage: 6
pad_latent_to_max: True

# 模型与训练参数
model_id: "meta-llama/Llama-3.2-3B-Instruct"
bf16: True
lr: !!float "1e-5"
batch_size_training: 32   # 显存吃紧，调小
gradient_accumulation_steps: 1 # 保持总 batch size = 32

# 通用设置
save_only_improve: False
uniform_prob: 0.5
load_model_path: None
seed: 0
resume: 0
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
debug: False
num_epochs: 25
weight_decay: 0.01
train_ratio: 0.2